// Calibrated model parameters.
//
// Generated by `npm run calibrate` from two years of realised close-to-open
// gaps. Nothing here is a guess: every number is fitted, and the band is
// validated by a coverage test that checks what fraction of historical gaps
// actually landed inside it.

import raw from "./calibration.json";

export interface InstrumentCalibration {
  /** Fitted sensitivity to the blended BTC/ETH move over the same window. */
  beta: number;
  /** The conservative prior this replaced, kept for comparison. */
  priorBeta: number;
  /** Share of gap variance the proxy explains. */
  r2: number;
  samples: number;
  /** Residual standard deviation on an overnight gap, in bps. */
  overnightSigmaBps: number;
  weekendSigmaBps: number;
  /** Share of historical gaps that landed inside the published band. */
  coveragePct: number | null;
}

export interface Calibration {
  generatedAt: string;
  method: string;
  /**
   * Fitted exponent for sigma proportional to hours^k.
   *
   * Measured at roughly 0.107, not the 0.5 a random walk in calendar time would
   * imply. A weekend is about 3.7x the hours of an overnight gap yet is only
   * marginally wider, because information arrives around the close and the open
   * rather than evenly through Saturday. The earlier sqrt(t) model overstated
   * weekend risk by a wide margin.
   */
  timeExponent: number;
  /** Gap length the per-instrument base sigma is anchored at. */
  referenceGapHours: number;
  instruments: Record<string, InstrumentCalibration>;
}

export const CALIBRATION = raw as Calibration;

/** Two-sided 95% interval, matching the coverage test. */
export const Z_95 = 1.96;

/** Fallback for an instrument with no fitted row yet. */
const FALLBACK: InstrumentCalibration = {
  beta: 0,
  priorBeta: 0,
  r2: 0,
  samples: 0,
  // Deliberately wide: an uncalibrated instrument should read as uncertain,
  // not as confident.
  overnightSigmaBps: 250,
  weekendSigmaBps: 280,
  coveragePct: null,
};

export function calibrationFor(ticker: string): InstrumentCalibration {
  return CALIBRATION.instruments[ticker] ?? FALLBACK;
}

export function isCalibrated(ticker: string): boolean {
  return Boolean(CALIBRATION.instruments[ticker]);
}

/**
 * Expected standard deviation of the gap for this instrument, in bps.
 *
 * Scales the fitted overnight sigma by the measured time exponent rather than
 * an assumed one.
 */
export function gapSigmaBps(ticker: string, gapHours: number): number {
  const cal = calibrationFor(ticker);
  const ref = CALIBRATION.referenceGapHours || 17.5;
  const hours = Math.max(0.25, gapHours);
  return cal.overnightSigmaBps * Math.pow(hours / ref, CALIBRATION.timeExponent);
}
